[tool.pytest.ini_options]
filterwarnings = [
    "ignore:::ray.*",
    "ignore:Deprecated call to `pkg_resources\\.declare_namespace\\('.*'\\):DeprecationWarning",
    "ignore::DeprecationWarning:google.rpc",
]